# Uncomment this line to define a global platform for your project
 platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PhotoTravel' do

pod 'Facebook-iOS-SDK', '~> 3.20'
pod 'Parse', '~> 1.4'
pod 'ParseFacebookUtils', '~> 1.4'

end

target 'PhotoTravelTests' do

end

